@startuml 
skinparam BorderColor #blue9932CC 
skinparam backgroundcolor AntiqueWhite/white 
title 
这里是标题
end title 
footer  copyright (c) imfly 2016.08.09 http://bitcoin-on-nodejs.ebookchain.org 
header 《Nodejs开发加密货币》分析用图

  [
    [
        {
            "name": "isASCII",
            "params": [
                "str",
                "extended"
            ]
        }
    ],
    [
        {
            "name": "OutTransfer",
            "params": []
        },
        {
            "name": "create",
            "params": [
                "data",
                "trs"
            ],
            "visiable": "Public"
        },
        {
            "name": "calculateFee",
            "params": [
                "trs",
                "sender"
            ],
            "visiable": "Public"
        }
    ],
    [
        {
            "name": "DApps",
            "params": [
                "cb",
                "scope"
            ]
        },
        {
            "name": "attachApi",
            "params": [],
            "visiable": "privated"
        },
        {
            "package": "library",
            "lib": "network"
        },
        {
            "name": "get",
            "params": [
                "id",
                "cb"
            ],
            "visiable": "privated"
        },
        {
            "package": "library",
            "lib": "dbLite"
        },
        {
            "name": "getByIds",
            "params": [
                "ids",
                "cb"
            ],
            "visiable": "privated"
        },
        {
            "package": "library",
            "lib": "dbLite"
        },
        {
            "name": "downloadSiaFile",
            "params": [
                "id",
                "ascii",
                "icon",
                "path",
                "cb"
            ],
            "visiable": "privated"
        },
        {
            "package": "modules",
            "lib": "sia"
        },
        {
            "name": "message",
            "params": [
                "dappid",
                "body",
                "cb"
            ],
            "visiable": "Public"
        },
        {
            "name": "onBind",
            "params": [
                "scope"
            ],
            "visiable": "Public"
        },
        {
            "name": "onBlockchainReady",
            "params": [],
            "visiable": "Public"
        },
        {
            "name": "onNewBlock",
            "params": [
                "block",
                "broadcast"
            ],
            "visiable": "Public"
        },
        {
            "name": "getGenesis",
            "params": [
                "req",
                "cb"
            ],
            "visiable": "shared"
        },
        {
            "package": "library",
            "lib": "dbLite"
        },
        {
            "name": "setReady",
            "params": [
                "req",
                "cb"
            ],
            "visiable": "shared"
        }
    ]
]
@enduml