[
    {
        "isASCII": "FunctionDeclaration"
    },
    {
        "OutTransfer": "FunctionDeclaration"
    },
    {
        "InTransfer": "FunctionDeclaration"
    },
    {
        "DApp": "FunctionDeclaration"
    },
    {
        "DApps": "FunctionDeclaration"
    },
    {
        "remove": "FunctionDeclaration"
    },
    {
        "error": "FunctionDeclaration"
    }
]